/*
 * DagsHub API
 * This API is used to interact with DagsHub. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The File model module.
 * @module model/File
 * @version 1.0.0
 */
export class File {
  /**
   * Constructs a new <code>File</code>.
   * @alias module:model/File
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>File</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/File} obj Optional instance to populate.
   * @return {module:model/File} The populated <code>File</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new File();
      if (data.hasOwnProperty('path'))
        obj.path = ApiClient.convertToType(data['path'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('size'))
        obj.size = ApiClient.convertToType(data['size'], 'Number');
      if (data.hasOwnProperty('hash'))
        obj.hash = ApiClient.convertToType(data['hash'], 'String');
      if (data.hasOwnProperty('versioning'))
        obj.versioning = ApiClient.convertToType(data['versioning'], 'String');
      if (data.hasOwnProperty('download_url'))
        obj.downloadUrl = ApiClient.convertToType(data['download_url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} path
 */
File.prototype.path = undefined;

/**
 * @member {String} type
 */
File.prototype.type = undefined;

/**
 * @member {Number} size
 */
File.prototype.size = undefined;

/**
 * @member {String} hash
 */
File.prototype.hash = undefined;

/**
 * @member {String} versioning
 */
File.prototype.versioning = undefined;

/**
 * @member {String} downloadUrl
 */
File.prototype.downloadUrl = undefined;

