/*
 * DagsHub API
 * This API is used to interact with DagsHub. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {WebhookConfig} from './WebhookConfig';
import {WebhookEvents} from './WebhookEvents';

/**
 * The HooksIdBody model module.
 * @module model/HooksIdBody
 * @version 1.0.0
 */
export class HooksIdBody {
  /**
   * Constructs a new <code>HooksIdBody</code>.
   * @alias module:model/HooksIdBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HooksIdBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HooksIdBody} obj Optional instance to populate.
   * @return {module:model/HooksIdBody} The populated <code>HooksIdBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HooksIdBody();
      if (data.hasOwnProperty('config'))
        obj.config = WebhookConfig.constructFromObject(data['config']);
      if (data.hasOwnProperty('events'))
        obj.events = WebhookEvents.constructFromObject(data['events']);
      if (data.hasOwnProperty('active'))
        obj.active = ApiClient.convertToType(data['active'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {module:model/WebhookConfig} config
 */
HooksIdBody.prototype.config = undefined;

/**
 * @member {module:model/WebhookEvents} events
 */
HooksIdBody.prototype.events = undefined;

/**
 * Weather the hook is actually triggered on pushes or not. Ignore this field to leave it unchanged.
 * @member {Boolean} active
 */
HooksIdBody.prototype.active = undefined;

