# coding: utf-8

"""
    DagsHub API

    This API is used to interact with DagsHub.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.webhooks_api import WebhooksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self):
        self.api = WebhooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_hook(self):
        """Test case for create_hook

        Create a hook  # noqa: E501
        """
        pass

    def test_delete_hook(self):
        """Test case for delete_hook

        Delete a hook  # noqa: E501
        """
        pass

    def test_edit_hook(self):
        """Test case for edit_hook

        Edit a hook  # noqa: E501
        """
        pass

    def test_list_hooks(self):
        """Test case for list_hooks

        List hooks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
