# coding: utf-8

"""
    DagsHub API

    This API is used to interact with DagsHub.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.issue_labels import IssueLabels  # noqa: E501
from swagger_client.rest import ApiException


class TestIssueLabels(unittest.TestCase):
    """IssueLabels unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssueLabels(self):
        """Test IssueLabels"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.issue_labels.IssueLabels()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
