# coding: utf-8

"""
    DagsHub API

    This API is used to interact with DagsHub.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.content_api import ContentApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContentApi(unittest.TestCase):
    """ContentApi unit test stubs"""

    def setUp(self):
        self.api = ContentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_archive(self):
        """Test case for get_archive

        Download archive  # noqa: E501
        """
        pass

    def test_get_content(self):
        """Test case for get_content

        Get data from a folder in repository  # noqa: E501
        """
        pass

    def test_get_raw(self):
        """Test case for get_raw

        Download raw content  # noqa: E501
        """
        pass

    def test_upload_content(self):
        """Test case for upload_content

        Upload data to a repository  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
