# coding: utf-8

"""
    DagsHub API

    This API is used to interact with DagsHub.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.post_issue import PostIssue  # noqa: E501
from swagger_client.rest import ApiException


class TestPostIssue(unittest.TestCase):
    """PostIssue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostIssue(self):
        """Test PostIssue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.post_issue.PostIssue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
