/*
 * DagsHub API
 * This API is used to interact with DagsHub. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for BranchesApi
 */
@Ignore
public class BranchesApiTest {

    private final BranchesApi api = new BranchesApi();

    /**
     * Get Branch
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getBranchTest() throws Exception {
        String owner = null;
        String repo = null;
        String branch = null;
        api.getBranch(owner, repo, branch);

        // TODO: test validations
    }
    /**
     * List Branches
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listBranchesTest() throws Exception {
        String owner = null;
        String repo = null;
        api.listBranches(owner, repo);

        // TODO: test validations
    }
}
