/* 
 * DagsHub API
 *
 * This API is used to interact with DagsHub. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WebhookEvents
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebhookEventsTests
    {
        // TODO uncomment below to declare an instance variable for WebhookEvents
        //private WebhookEvents instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebhookEvents
            //instance = new WebhookEvents();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebhookEvents
        /// </summary>
        [Test]
        public void WebhookEventsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebhookEvents
            //Assert.IsInstanceOfType<WebhookEvents> (instance, "variable 'instance' is a WebhookEvents");
        }



    }

}
