# DagsHub API
#
# This API is used to interact with DagsHub. 
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Files Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Files <- R6::R6Class(
  'Files',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      FilesObject <- list()

      FilesObject
    },
    fromJSON = function(FilesJson) {
      FilesObject <- jsonlite::fromJSON(FilesJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(FilesJson) {
      FilesObject <- jsonlite::fromJSON(FilesJson)
    }
  )
)
