# DagsHub API
#
# This API is used to interact with DagsHub. 
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PostIssue Class
#'
#' @field title 
#' @field body 
#' @field assignee 
#' @field milestone 
#' @field labels 
#' @field closed 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PostIssue <- R6::R6Class(
  'PostIssue',
  public = list(
    `title` = NULL,
    `body` = NULL,
    `assignee` = NULL,
    `milestone` = NULL,
    `labels` = NULL,
    `closed` = NULL,
    initialize = function(`title`, `body`, `assignee`, `milestone`, `labels`, `closed`){
      if (!missing(`title`)) {
        stopifnot(R6::is.R6(`title`))
        self$`title` <- `title`
      }
      if (!missing(`body`)) {
        stopifnot(R6::is.R6(`body`))
        self$`body` <- `body`
      }
      if (!missing(`assignee`)) {
        stopifnot(R6::is.R6(`assignee`))
        self$`assignee` <- `assignee`
      }
      if (!missing(`milestone`)) {
        stopifnot(R6::is.R6(`milestone`))
        self$`milestone` <- `milestone`
      }
      if (!missing(`labels`)) {
        stopifnot(R6::is.R6(`labels`))
        self$`labels` <- `labels`
      }
      if (!missing(`closed`)) {
        stopifnot(R6::is.R6(`closed`))
        self$`closed` <- `closed`
      }
    },
    toJSON = function() {
      PostIssueObject <- list()
      if (!is.null(self$`title`)) {
        PostIssueObject[['title']] <- self$`title`$toJSON()
      }
      if (!is.null(self$`body`)) {
        PostIssueObject[['body']] <- self$`body`$toJSON()
      }
      if (!is.null(self$`assignee`)) {
        PostIssueObject[['assignee']] <- self$`assignee`$toJSON()
      }
      if (!is.null(self$`milestone`)) {
        PostIssueObject[['milestone']] <- self$`milestone`$toJSON()
      }
      if (!is.null(self$`labels`)) {
        PostIssueObject[['labels']] <- self$`labels`$toJSON()
      }
      if (!is.null(self$`closed`)) {
        PostIssueObject[['closed']] <- self$`closed`$toJSON()
      }

      PostIssueObject
    },
    fromJSON = function(PostIssueJson) {
      PostIssueObject <- jsonlite::fromJSON(PostIssueJson)
      if (!is.null(PostIssueObject$`title`)) {
        titleObject <- Title$new()
        titleObject$fromJSON(jsonlite::toJSON(PostIssueObject$title, auto_unbox = TRUE))
        self$`title` <- titleObject
      }
      if (!is.null(PostIssueObject$`body`)) {
        bodyObject <- Body$new()
        bodyObject$fromJSON(jsonlite::toJSON(PostIssueObject$body, auto_unbox = TRUE))
        self$`body` <- bodyObject
      }
      if (!is.null(PostIssueObject$`assignee`)) {
        assigneeObject <- Assignee$new()
        assigneeObject$fromJSON(jsonlite::toJSON(PostIssueObject$assignee, auto_unbox = TRUE))
        self$`assignee` <- assigneeObject
      }
      if (!is.null(PostIssueObject$`milestone`)) {
        milestoneObject <- Milestone$new()
        milestoneObject$fromJSON(jsonlite::toJSON(PostIssueObject$milestone, auto_unbox = TRUE))
        self$`milestone` <- milestoneObject
      }
      if (!is.null(PostIssueObject$`labels`)) {
        labelsObject <- Labels$new()
        labelsObject$fromJSON(jsonlite::toJSON(PostIssueObject$labels, auto_unbox = TRUE))
        self$`labels` <- labelsObject
      }
      if (!is.null(PostIssueObject$`closed`)) {
        closedObject <- Closed$new()
        closedObject$fromJSON(jsonlite::toJSON(PostIssueObject$closed, auto_unbox = TRUE))
        self$`closed` <- closedObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "title": %s,
           "body": %s,
           "assignee": %s,
           "milestone": %s,
           "labels": %s,
           "closed": %s
        }',
        self$`title`$toJSON(),
        self$`body`$toJSON(),
        self$`assignee`$toJSON(),
        self$`milestone`$toJSON(),
        self$`labels`$toJSON(),
        self$`closed`$toJSON()
      )
    },
    fromJSONString = function(PostIssueJson) {
      PostIssueObject <- jsonlite::fromJSON(PostIssueJson)
      TitleObject <- Title$new()
      self$`title` <- TitleObject$fromJSON(jsonlite::toJSON(PostIssueObject$title, auto_unbox = TRUE))
      BodyObject <- Body$new()
      self$`body` <- BodyObject$fromJSON(jsonlite::toJSON(PostIssueObject$body, auto_unbox = TRUE))
      AssigneeObject <- Assignee$new()
      self$`assignee` <- AssigneeObject$fromJSON(jsonlite::toJSON(PostIssueObject$assignee, auto_unbox = TRUE))
      MilestoneObject <- Milestone$new()
      self$`milestone` <- MilestoneObject$fromJSON(jsonlite::toJSON(PostIssueObject$milestone, auto_unbox = TRUE))
      LabelsObject <- Labels$new()
      self$`labels` <- LabelsObject$fromJSON(jsonlite::toJSON(PostIssueObject$labels, auto_unbox = TRUE))
      ClosedObject <- Closed$new()
      self$`closed` <- ClosedObject$fromJSON(jsonlite::toJSON(PostIssueObject$closed, auto_unbox = TRUE))
    }
  )
)
