# DagsHub API
#
# This API is used to interact with DagsHub. 
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' RepoHooksBody Class
#'
#' @field type 
#' @field config 
#' @field events 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RepoHooksBody <- R6::R6Class(
  'RepoHooksBody',
  public = list(
    `type` = NULL,
    `config` = NULL,
    `events` = NULL,
    initialize = function(`type`, `config`, `events`){
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`config`)) {
        stopifnot(R6::is.R6(`config`))
        self$`config` <- `config`
      }
      if (!missing(`events`)) {
        stopifnot(R6::is.R6(`events`))
        self$`events` <- `events`
      }
    },
    toJSON = function() {
      RepoHooksBodyObject <- list()
      if (!is.null(self$`type`)) {
        RepoHooksBodyObject[['type']] <- self$`type`
      }
      if (!is.null(self$`config`)) {
        RepoHooksBodyObject[['config']] <- self$`config`$toJSON()
      }
      if (!is.null(self$`events`)) {
        RepoHooksBodyObject[['events']] <- self$`events`$toJSON()
      }

      RepoHooksBodyObject
    },
    fromJSON = function(RepoHooksBodyJson) {
      RepoHooksBodyObject <- jsonlite::fromJSON(RepoHooksBodyJson)
      if (!is.null(RepoHooksBodyObject$`type`)) {
        self$`type` <- RepoHooksBodyObject$`type`
      }
      if (!is.null(RepoHooksBodyObject$`config`)) {
        configObject <- WebhookConfig$new()
        configObject$fromJSON(jsonlite::toJSON(RepoHooksBodyObject$config, auto_unbox = TRUE))
        self$`config` <- configObject
      }
      if (!is.null(RepoHooksBodyObject$`events`)) {
        eventsObject <- WebhookEvents$new()
        eventsObject$fromJSON(jsonlite::toJSON(RepoHooksBodyObject$events, auto_unbox = TRUE))
        self$`events` <- eventsObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "type": %s,
           "config": %s,
           "events": %s
        }',
        self$`type`,
        self$`config`$toJSON(),
        self$`events`$toJSON()
      )
    },
    fromJSONString = function(RepoHooksBodyJson) {
      RepoHooksBodyObject <- jsonlite::fromJSON(RepoHooksBodyJson)
      self$`type` <- RepoHooksBodyObject$`type`
      WebhookConfigObject <- WebhookConfig$new()
      self$`config` <- WebhookConfigObject$fromJSON(jsonlite::toJSON(RepoHooksBodyObject$config, auto_unbox = TRUE))
      WebhookEventsObject <- WebhookEvents$new()
      self$`events` <- WebhookEventsObject$fromJSON(jsonlite::toJSON(RepoHooksBodyObject$events, auto_unbox = TRUE))
    }
  )
)
