# DagsHub API
#
# This API is used to interact with DagsHub. 
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Title Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Title <- R6::R6Class(
  'Title',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      TitleObject <- list()

      TitleObject
    },
    fromJSON = function(TitleJson) {
      TitleObject <- jsonlite::fromJSON(TitleJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(TitleJson) {
      TitleObject <- jsonlite::fromJSON(TitleJson)
    }
  )
)
