# DagsHub API
#
# This API is used to interact with DagsHub. 
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' WebhookEvents Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
WebhookEvents <- R6::R6Class(
  'WebhookEvents',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      WebhookEventsObject <- list()

      WebhookEventsObject
    },
    fromJSON = function(WebhookEventsJson) {
      WebhookEventsObject <- jsonlite::fromJSON(WebhookEventsJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(WebhookEventsJson) {
      WebhookEventsObject <- jsonlite::fromJSON(WebhookEventsJson)
    }
  )
)
