/*
 * DagsHub API
 *
 * This API is used to interact with DagsHub. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateRepo struct {
	// name of the repository
	Name string `json:"name"`
	// A short description of the repository
	Description string `json:"description,omitempty"`
	// Either true to create a private repository, or false to create a public one.
	Private bool `json:"private,omitempty"`
	// Pass true to create an initial commit with README, .gitignore and LICENSE.
	AutoInit bool `json:"auto_init,omitempty"`
	// Desired language .gitignore templates to apply. Use the name of the templates.
	Gitignores string `json:"gitignores,omitempty"`
	// Desired LICENSE template to apply. Use the name of the template.
	License string `json:"license,omitempty"`
	// Desired README template to apply. Use the name of the template.
	Readme string `json:"readme,omitempty"`
}
