/*
 * DagsHub API
 *
 * This API is used to interact with DagsHub. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Issue struct {
	Id int32 `json:"id,omitempty"`
	Number int32 `json:"number,omitempty"`
	User *User `json:"user,omitempty"`
	Title string `json:"title"`
	Body string `json:"body"`
	Labels []IssueLabels `json:"labels"`
	Milestone *IssueMilestone `json:"milestone"`
	Assignee *IssueAssignee `json:"assignee"`
	State string `json:"state,omitempty"`
	Comments int32 `json:"comments,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
	PullRequest *interface{} `json:"pull_request,omitempty"`
	Closed bool `json:"closed"`
}
