/*
 * DagsHub API
 *
 * This API is used to interact with DagsHub. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type IssueLabels struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Color string `json:"color,omitempty"`
	Url string `json:"url,omitempty"`
}
